# Generated by Django 4.2.29 on 2026-03-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_the_view', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
